using System;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Collections.Generic;

namespace RestaurantServer.Contracts
{
    /// <summary>
    /// A system event that can be generated by either the physical security system 
    /// or the green energy management system.
    /// </summary>
    [DataContract]
    public class Event
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        public Event(string description, DateTime eventTime)
        {
            EventDescription = description;
            EventID = Guid.NewGuid().ToString();
            EventTime = eventTime;
        }

        [DataMember]
        public string EventDescription { get; private set; }

        [DataMember]
        public string EventID { get; private set; }

        [DataMember]
        public DateTime EventTime { get; private set; }
    }

    /// <summary>
    /// Event that is pushed from the server to its clients informing
    /// the completion time required for an order.
    /// </summary>
    [DataContract]
    public class OrderUpdate
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="id">Order ID.</param>
        /// <param name="minutes">Number of minutes required for order to finish.</param>
        public OrderUpdate(int id, decimal minutes)
        {
            ID = id;
            Minutes = minutes;
        }

        [DataMember]
        public int ID { get; private set; }

        [DataMember]
        public decimal Minutes { get; private set; }
    }

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class Order
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="id">Order ID.</param>
        /// <param name="items">Items requested in this order. Key value pair
        /// using the format <item name, quantity>.</param>
        public Order(int id, Dictionary<string, int> items)
        {
            ID = id;
            Items = items;
        }

        public Dictionary<string, int> Items { get; private set; }

        public int ID { get; private set; }
    }
}
