using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using RestaurantServer.Contracts;
using System.IO;


namespace RestaurantServer.Utilities
{
    /// <summary>
    /// An event listener that will interface with a command-line UI to output
    /// a text description of events.
    /// </summary>
    public class SystemLogger : IEventCallback
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        private SystemLogger() 
        {
            SystemEventPublisher.Instance.SubscribeListener(this);
        }

        /// <summary>
        /// Will log any event generated by the home security system tot he console.
        /// </summary>
        public void OnPublishedEvent(Event e)
        {
            LogToConsole(string.Format("Event: {0}", e.EventDescription));
        }

        /// <summary>
        /// Generates an 'Informative' event to be logged. Should be used only
        /// for system-level notifications.
        /// </summary>
        /// <param name="log">The message to be logged.</param>
        public void LogToConsole(string log)
        {
            Console.WriteLine("[{0}] - {1}", DateTime.Now.ToString(), log);
        }

        /// <summary>
        /// Log an entry to a text file.
        /// </summary>
        /// <param name="log"></param>
        public void WriteLog(string log)
        {
            string path = @"C:\temp\log.txt";

            if (File.Exists(path))
            {
                File.Delete(path);
            }

            using(StreamWriter sw = new StreamWriter(path))
            {
                sw.WriteLine(log);
            }
        }

        /// <summary>
        /// Singleton instance of the this 'SystemLogger' type
        /// </summary>
        public static SystemLogger Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new SystemLogger();
                }

                return _instance;
            }
        }

        private static SystemLogger _instance;

        public void OrderCompletionTimePushed(OrderUpdate update)
        {
            return;
        }

        public void NewOrder(Order update, Customer customer)
        {
            LogToConsole(string.Format("Order #{0} received for '{1}'.", update.ID.ToString(), customer.Name)); 
        }
    }
}
